### ISSUE TITLE
Port to i18next v4 format

### ISSUE THREAD

**Issue by lazka** [digital-blueprint/toolkit#31]
Now that we have switched to i18next-parser we can also switch the json format to the newer version.

https://www.i18next.com/misc/json-format#i18next-json-v4

Todo:

* switch i18next-parser to v4
* switch the i18next init to v4
* port all apps, foreach:
  * update toolkit
  * switch i18next-parser to v4

v4 requires https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/intl/pluralrules -> https://caniuse.com/intl-pluralrules

Which means we would drop support for Safari<13. If we do this then we need to add a check for `(typeof Intl === 'undefined' || !Intl.PluralRules)` to the browser check script.

**Comment by lazka** [comment]
We have dropped Safari<13 now, so this could be started.

**Comment by ruxandragherman** [comment]
Issue fixed
